version: '3.8'

services:
  dashboard:
    build: .
    container_name: swimming_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data # Mount local data folder to container
    restart: always
